name: build

on: [push, pull_request]

env:
  FORCE_COLOR: 3

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: yarn
      - run: yarn run prettier-check
      - run: yarn run eslint
      - run: yarn run build
      - name: release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn run semantic-release
